### DISCUSSION TITLE
Unstyled lists with `role="list"` attr

### DISCUSSION THREAD

**Discussion by zarahzachz** [CMSgov/design-system#2115] [Ideas]
We use the class `ds-c-list--bare` to create unstyled lists (list elements without a list marker style). This can cause [accessibility problems for Safari users](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#accessibility_concerns).

I've tried to address this issue using documentation in our site, but I wonder if we should have a better internal solution?

I like the idea of tying styles to a11y solutions and was thinking a better way to create unstyled lists would be to attach those style rules to the `role="list"` attribute (which is the fix for this bug)?

It could look like this:

```css
ul[role="list"],
ol[role="list"] {
  list-style: none;
  /* whatever else we do to unstyled lists */
}
``` 

or... 

```css
.ds-c-list[role="list"] {
  list-style: none;
  /* whatever else we do to unstyled lists */
}
``` 

The benefits for a solution like this:
1. It guarantees this attribute is added when an unstyled list class is used
2. Users currently need to remember to add the CSS class **and** HTML attribute to correctly style unstyled lists and this simplifies that

The drawback is this is probably a very widely used style and pretty hard to change now that it's in the wild.
