### ISSUE TITLE
Fix disabled state in MGov's child button styles

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#1548]
**Describe the bug**

Some aspects of disabled state in the MGov Primary Alt Button, among others, is overridden by other CSS

**To Reproduce**

1. Go to the [Button page on MGov docs](https://github.cms.gov/pages/MedicareGov/mgov-design-system/components/button/)
2. In devtools/inspector, find, e.g., the Primary Alt Button, `:disabled` state
3. Again in devtools, toggle `:hover` and `:active` states
4. See the button state change incorrectly (`background-color` and `color`)
5. I can't entirely reproduce here, but in MCT's repo, with the CSS shown below, if I remove the nested `:focus` selector, toggling `:focus` also incorrectly changes the button's `background-color` and `color` (only a focus ring should show up)

**Expected behavior**

See the buttons in the CMSDS docs, and the MGov Default button. The `:disabled` state's `background-color`, `color` and behavior (e.g. `pionter-events: none`) all override declarations for other states, such as `:hover`, `:active`, and `:focus`

**Screenshots**

See `:disabled` button with `:active` state has changed color, compared to the one above (not `:active`)

<img src="https://user-images.githubusercontent.com/771447/151081447-25bc1b46-f629-4514-aff4-650b73c8e2f0.png" width="525" />

**Desktop (please complete the following information):**

 - OS: Mac OSX 10.15.7
 - Browser: Chrome, both desktop and responsive mode (same results in other desktop browsers)
 - Version: 97.0.4692.99

**Smartphone (please complete the following information):**

Did not test

**Additional context**

In the MCT repo, I've added the following workaround for Button Primary Alt, and I'm not sure what the minimum necessary is to achieve the desired results. The fix should also take into account the use of the class `ds-c-button--disabled`, and not just the `:disabled` selector.

```css
.ds-c-button--primary-alt:disabled {
  &:active,
  &:hover,
  &:focus {
    background-color: $color-gray-lighter !important;
    color: $color-gray-dark !important;
    @extend .ds-c-button--disabled;
  }
}
```
